#!/usr/bin/env ruby

require 'git-rank'
require 'git-rank/options'
require 'git-rank/printer'

options = GitRank::Options.parse
authors = GitRank.calculate(options)
GitRank::Printer.print(authors, options)
